version: '3'
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - "D:/DJ-Blog/config:/config"
    depends_on:
      - mysql
      - search
    ports:
      - "8000:8000"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dj_blog

  search:
    image: public.ecr.aws/zinclabs/zinc:latest
    volumes:
      - "D:/DJ-Blog/data:/data"
    environment:
      ZINC_FIRST_ADMIN_USER: admin
      ZINC_FIRST_ADMIN_PASSWORD: admin123456
      ZINC_DATA_PATH: /data


