version: '3'
services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - "D:/DJ-Blog/config:/config"
    depends_on:
      - mysql
    ports:
      - "8000:8000"
  mysql:
    image: mysql:latest
    volumes:
      - "D:/DJ-Blog/mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dj_blog


