server:
  port: "8000"

database:
  host: "127.0.0.1"
  port: "3306"
  username: "root"
  password: "123456"
  dbname: "dj_blog"

github:
  clientId: ""
  clientSecret: ""

session:
  authenticationKey: "XXXXXXXXXXXXXXXX" # 十六位随机字符串
  encryptionKey: "XXXXXXXXXXXXXXXX" # 十六位随机字符串







