server:
  port: 8000

template:
  path:
    - ./views/front/*.html
    - ./views/example/*.html
static:
  path: ./static

database:
  type: sqlite
  mysql:
    host: mysql
    port: 3306
    username: root
    password: 123456
    dbname: dj_blog

  sqlite:
    dbname: dj_blog.db

log:
  path: logs/logs.log

github:
  clientId:
  clientSecret:

zinc:
  username:
  password:
  endpoint:
  indexName: