definitions:
  model.CategoryModel:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  model.TagModel:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  request.ArticleCreateReq:
    properties:
      categories:
        items:
          type: integer
        type: array
      imgUrl:
        type: string
      originContent:
        example: required
        type: string
      parseContent:
        example: required
        type: string
      tags:
        items:
          type: integer
        type: array
      title:
        example: required
        type: string
    type: object
  request.ArticleUpdateReq:
    properties:
      categories:
        items:
          type: integer
        type: array
      id:
        type: integer
      imgUrl:
        type: string
      originContent:
        example: required
        type: string
      parseContent:
        example: required
        type: string
      tags:
        items:
          type: integer
        type: array
      title:
        example: required
        type: string
    type: object
  request.UserLoginReq:
    properties:
      password:
        example: required;min:6;max:20
        type: string
      username:
        example: required;min:2;max:20
        type: string
    type: object
  request.UserRegisterReq:
    properties:
      avatar_url:
        type: string
      password:
        example: required;min:6;max:20
        type: string
      username:
        description: |-
          example 是 swagger 文档中的示例的关键字，用于生成 swagger 文档。
          这里的值并没有使用一个真的示例，而是用了这个数据的限制作为示例。
          TODO: 利用这个example值，做自动化的测试，限制条件之间用分号分隔，如：min:2,max:20
        example: required;min:2;max:20
        type: string
    type: object
  response.Status:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  service.Article:
    properties:
      categories:
        items:
          $ref: '#/definitions/model.CategoryModel'
        type: array
      createdAt:
        type: string
      id:
        type: integer
      imgUrl:
        type: string
      originContent:
        type: string
      parseContent:
        type: string
      tags:
        items:
          $ref: '#/definitions/model.TagModel'
        type: array
      title:
        type: string
      updatedAt:
        type: string
      userId:
        type: integer
    type: object
  service.User:
    properties:
      articles:
        items:
          $ref: '#/definitions/service.Article'
        type: array
      avatarUrl:
        example: https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png
        type: string
      createdAt:
        example: "2021-01-01 00:00:00"
        type: string
      id:
        example: 1
        type: integer
      password:
        example: "123456"
        type: string
      updatedAt:
        example: "2021-01-01 00:00:00"
        type: string
      username:
        example: admin
        type: string
    type: object
info:
  contact: {}
  description: DJ-Blog API文档
  title: DJ-Blog API文档
  version: "1.0"
paths:
  /article:
    get:
      description: 获取文章列表
      parameters:
      - description: 页码
        in: query
        name: pageNum
        required: true
        type: integer
      - description: 每页数量
        in: query
        name: pageSize
        required: true
        type: integer
      responses:
        "200":
          description: ok
          schema:
            allOf:
            - $ref: '#/definitions/response.Status'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/service.Article'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Status'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Status'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/response.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Status'
      summary: 获取文章列表
      tags:
      - Article
    post:
      consumes:
      - application/json
      description: 创建文章
      parameters:
      - description: 文章信息
        in: body
        name: ArticleCreateRequest
        required: true
        schema:
          $ref: '#/definitions/request.ArticleCreateReq'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            allOf:
            - $ref: '#/definitions/response.Status'
            - properties:
                data:
                  $ref: '#/definitions/service.Article'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Status'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/response.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Status'
      summary: 创建文章
      tags:
      - Article
  /article/{id}:
    delete:
      consumes:
      - application/json
      description: 删除文章
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            allOf:
            - $ref: '#/definitions/response.Status'
            - properties:
                data:
                  type: integer
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Status'
        "422":
          description: Unprocessable Entity"'
          schema:
            $ref: '#/definitions/response.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Status'
      summary: 删除文章
      tags:
      - Article
    get:
      description: 获取文章详情
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: ok
          schema:
            allOf:
            - $ref: '#/definitions/response.Status'
            - properties:
                data:
                  $ref: '#/definitions/service.Article'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Status'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Status'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/response.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Status'
      summary: 获取文章详情
      tags:
      - Article
    put:
      consumes:
      - application/json
      description: 更新文章
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      - description: 文章信息
        in: body
        name: ArticleUpdateRequest
        required: true
        schema:
          $ref: '#/definitions/request.ArticleUpdateReq'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            allOf:
            - $ref: '#/definitions/response.Status'
            - properties:
                data:
                  $ref: '#/definitions/service.Article'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Status'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/response.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Status'
      summary: 更新文章
      tags:
      - Article
  /article/category/{id}:
    get:
      description: 根据分类获取文章列表
      parameters:
      - description: 分类的ID
        in: path
        name: id
        required: true
        type: integer
      - description: 页码
        in: query
        name: pageNum
        required: true
        type: integer
      - description: 每页数量
        in: query
        name: pageSize
        required: true
        type: integer
      responses:
        "200":
          description: ok
          schema:
            allOf:
            - $ref: '#/definitions/response.Status'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/service.Article'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Status'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Status'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/response.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Status'
      summary: 根据分类获取文章列表
      tags:
      - Article
  /article/search:
    get:
      description: 通过关键词搜索文章
      parameters:
      - description: 关键词
        in: query
        name: keyword
        required: true
        type: string
      - description: 页码
        in: query
        name: pageNum
        required: true
        type: integer
      - description: 每页数量
        in: query
        name: pageSize
        required: true
        type: integer
      responses:
        "200":
          description: ok
          schema:
            allOf:
            - $ref: '#/definitions/response.Status'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/service.Article'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Status'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Status'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/response.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Status'
      summary: 搜索文章
      tags:
      - Article
  /article/tag:
    get:
      description: 获取所有标签
      responses:
        "200":
          description: ok
          schema:
            allOf:
            - $ref: '#/definitions/response.Status'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.TagModel'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Status'
      summary: 获取所有标签
      tags:
      - Article
  /article/tag/{id}:
    get:
      description: 根据标签获取文章列表
      parameters:
      - description: 标签的ID
        in: path
        name: id
        required: true
        type: integer
      - description: 页码
        in: query
        name: pageNum
        required: true
        type: integer
      - description: 每页数量
        in: query
        name: pageSize
        required: true
        type: integer
      responses:
        "200":
          description: ok
          schema:
            allOf:
            - $ref: '#/definitions/response.Status'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/service.Article'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Status'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Status'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/response.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Status'
      summary: 根据标签获取文章列表
      tags:
      - Article
  /article/time:
    get:
      description: 根据文章创建时间由新到旧获取文章列表
      parameters:
      - description: 页码
        in: query
        name: pageNum
        required: true
        type: integer
      - description: 每页数量
        in: query
        name: pageSize
        required: true
        type: integer
      responses:
        "200":
          description: ok
          schema:
            allOf:
            - $ref: '#/definitions/response.Status'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/service.Article'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Status'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Status'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/response.Status'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Status'
      summary: 根据时间获取文章列表
      tags:
      - Article
  /category:
    get:
      description: 获取所有分类
      responses:
        "200":
          description: ok
          schema:
            allOf:
            - $ref: '#/definitions/response.Status'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/model.CategoryModel'
                  type: array
              type: object
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Status'
      summary: 获取所有分类
      tags:
      - Article
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 用户登录请求
        in: body
        name: UserLoginRequest
        required: true
        schema:
          $ref: '#/definitions/request.UserLoginReq'
      produces:
      - application/json
      responses:
        "200":
          description: 登录成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Status'
            - properties:
                data:
                  $ref: '#/definitions/service.User'
              type: object
        "401":
          description: 请求参数格式错误
          schema:
            $ref: '#/definitions/response.Status'
        "402":
          description: 请求参数不符合要求
          schema:
            $ref: '#/definitions/response.Status'
      summary: 用户登录
      tags:
      - User
  /user/logout:
    get:
      description: 退出登录
      responses:
        "200":
          description: 退出成功
          schema:
            $ref: '#/definitions/response.Status'
      summary: 退出登录
      tags:
      - User
  /user/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 用户注册请求
        in: body
        name: userRegisterRequest
        required: true
        schema:
          $ref: '#/definitions/request.UserRegisterReq'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Status'
            - properties:
                data:
                  $ref: '#/definitions/service.User'
              type: object
        "401":
          description: 请求参数格式错误
          schema:
            $ref: '#/definitions/response.Status'
        "402":
          description: 请求参数不符合要求
          schema:
            $ref: '#/definitions/response.Status'
      summary: 用户注册
      tags:
      - User
swagger: "2.0"
