definitions:
  response.Status:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  service.User:
    properties:
      avatarUrl:
        example: https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png
        type: string
      createdAt:
        example: "2021-01-01 00:00:00"
        type: string
      id:
        example: 1
        type: integer
      password:
        example: "123456"
        type: string
      updatedAt:
        example: "2021-01-01 00:00:00"
        type: string
      username:
        example: admin
        type: string
    type: object
info:
  contact: {}
  description: DJ-Blog API文档
  title: DJ-Blog API文档
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 用户名
        in: body
        name: username
        required: true
        schema:
          type: string
      - description: 密码
        in: body
        name: password
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "20000":
          description: 登录成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Status'
            - properties:
                data:
                  $ref: '#/definitions/service.User'
              type: object
        "40001":
          description: 请求参数格式错误
          schema:
            $ref: '#/definitions/response.Status'
        "40002":
          description: 请求参数不符合要求
          schema:
            $ref: '#/definitions/response.Status'
      summary: 用户登录
      tags:
      - 用户
swagger: "2.0"
