definitions:
  request.UserLoginReq:
    properties:
      password:
        example: required;min:6;max:20
        type: string
      username:
        example: required;min:2;max:20
        type: string
    type: object
  request.UserRegisterReq:
    properties:
      avatar_url:
        type: string
      password:
        example: required;min:6;max:20
        type: string
      username:
        description: |-
          example 是 swagger 文档中的示例的关键字，用于生成 swagger 文档。
          这里的值并没有使用一个真的示例，而是用了这个数据的限制作为示例。
          TODO: 利用这个example值，做自动化的测试，限制条件之间用分号分隔，如：min:2,max:20
        example: required;min:2;max:20
        type: string
    type: object
  response.Status:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  service.User:
    properties:
      avatarUrl:
        example: https://www.baidu.com/img/PCtm_d9c8750bed0b3c7d089fa7d55720d6cf.png
        type: string
      createdAt:
        example: "2021-01-01 00:00:00"
        type: string
      id:
        example: 1
        type: integer
      password:
        example: "123456"
        type: string
      updatedAt:
        example: "2021-01-01 00:00:00"
        type: string
      username:
        example: admin
        type: string
    type: object
info:
  contact: {}
  description: DJ-Blog API文档
  title: DJ-Blog API文档
  version: "1.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: 用户登录
      parameters:
      - description: 用户登录请求
        in: body
        name: userLoginRequest
        required: true
        schema:
          $ref: '#/definitions/request.UserLoginReq'
      produces:
      - application/json
      responses:
        "20000":
          description: 登录成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Status'
            - properties:
                data:
                  $ref: '#/definitions/service.User'
              type: object
        "40001":
          description: 请求参数格式错误
          schema:
            $ref: '#/definitions/response.Status'
        "40002":
          description: 请求参数不符合要求
          schema:
            $ref: '#/definitions/response.Status'
      summary: 用户登录
      tags:
      - 用户
  /user/logout:
    get:
      description: 退出登录
      responses:
        "20000":
          description: 退出成功
          schema:
            $ref: '#/definitions/response.Status'
      summary: 退出登录
      tags:
      - 用户
  /user/register:
    post:
      consumes:
      - application/json
      description: 用户注册
      parameters:
      - description: 用户注册请求
        in: body
        name: userRegisterRequest
        required: true
        schema:
          $ref: '#/definitions/request.UserRegisterReq'
      produces:
      - application/json
      responses:
        "20000":
          description: 注册成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Status'
            - properties:
                data:
                  $ref: '#/definitions/service.User'
              type: object
        "40001":
          description: 请求参数格式错误
          schema:
            $ref: '#/definitions/response.Status'
        "40002":
          description: 请求参数不符合要求
          schema:
            $ref: '#/definitions/response.Status'
      summary: 用户注册
      tags:
      - 用户
swagger: "2.0"
